### PR TITLE
added files for pieces, and place for piece icons

### PR DESCRIPTION
**Pull request by brennan-cesar**

### CODE REVIEW

**Review by Sabramz — CHANGES_REQUESTED** [review]
The pieces directory should be inside of the game directory, and the piece.py file should also be inside of the pieces directory since each of the pieces will inherit from it.

**Comment by brennan-cesar** [comment]
piece.py moved to inside pieces, but what do you mean by game directory? should i make a new folder and put that inside?

**Comment by Sabramz** [comment]
I guess you can't commit empty dirs or something. Just make a game dir and put the pieces dir in game.

**Review by brennan-cesar — COMMENTED** [review]
added game dir

**Review by Sabramz — APPROVED** [review]
looks good

**Pull request merged**
